/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type MarketTokenStruct = {
  itemId: BigNumberish;
  nftContract: string;
  tokenId: BigNumberish;
  seller: string;
  owner: string;
  price: BigNumberish;
  sold: boolean;
};

export type MarketTokenStructOutput = [
  BigNumber,
  string,
  BigNumber,
  string,
  string,
  BigNumber,
  boolean
] & {
  itemId: BigNumber;
  nftContract: string;
  tokenId: BigNumber;
  seller: string;
  owner: string;
  price: BigNumber;
  sold: boolean;
};

export interface KBMarketInterface extends utils.Interface {
  functions: {
    "createMarketSale(address,uint256)": FunctionFragment;
    "fetchItemsCreated()": FunctionFragment;
    "fetchMarketTokens()": FunctionFragment;
    "fetchMyNFTs()": FunctionFragment;
    "getListingPrice()": FunctionFragment;
    "makeMarketItem(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createMarketSale",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchItemsCreated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchMarketTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchMyNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeMarketItem",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarketSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchItemsCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMarketTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchMyNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeMarketItem",
    data: BytesLike
  ): Result;

  events: {
    "MarketTokenMinted(uint256,address,uint256,address,address,uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MarketTokenMinted"): EventFragment;
}

export type MarketTokenMintedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string, string, BigNumber, boolean],
  {
    itemId: BigNumber;
    nftContract: string;
    tokenId: BigNumber;
    seller: string;
    owner: string;
    price: BigNumber;
    sold: boolean;
  }
>;

export type MarketTokenMintedEventFilter =
  TypedEventFilter<MarketTokenMintedEvent>;

export interface KBMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KBMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createMarketSale(address,uint256)"(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fetchItemsCreated(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    "fetchItemsCreated()"(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    fetchMarketTokens(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    "fetchMarketTokens()"(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    fetchMyNFTs(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    "fetchMyNFTs()"(
      overrides?: CallOverrides
    ): Promise<[MarketTokenStructOutput[]]>;

    getListingPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getListingPrice()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    makeMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "makeMarketItem(address,uint256,uint256)"(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createMarketSale(
    nftContract: string,
    itemId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createMarketSale(address,uint256)"(
    nftContract: string,
    itemId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fetchItemsCreated(
    overrides?: CallOverrides
  ): Promise<MarketTokenStructOutput[]>;

  "fetchItemsCreated()"(
    overrides?: CallOverrides
  ): Promise<MarketTokenStructOutput[]>;

  fetchMarketTokens(
    overrides?: CallOverrides
  ): Promise<MarketTokenStructOutput[]>;

  "fetchMarketTokens()"(
    overrides?: CallOverrides
  ): Promise<MarketTokenStructOutput[]>;

  fetchMyNFTs(overrides?: CallOverrides): Promise<MarketTokenStructOutput[]>;

  "fetchMyNFTs()"(
    overrides?: CallOverrides
  ): Promise<MarketTokenStructOutput[]>;

  getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

  "getListingPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  makeMarketItem(
    nftContract: string,
    tokenId: BigNumberish,
    price: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "makeMarketItem(address,uint256,uint256)"(
    nftContract: string,
    tokenId: BigNumberish,
    price: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createMarketSale(address,uint256)"(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fetchItemsCreated(
      overrides?: CallOverrides
    ): Promise<MarketTokenStructOutput[]>;

    "fetchItemsCreated()"(
      overrides?: CallOverrides
    ): Promise<MarketTokenStructOutput[]>;

    fetchMarketTokens(
      overrides?: CallOverrides
    ): Promise<MarketTokenStructOutput[]>;

    "fetchMarketTokens()"(
      overrides?: CallOverrides
    ): Promise<MarketTokenStructOutput[]>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<MarketTokenStructOutput[]>;

    "fetchMyNFTs()"(
      overrides?: CallOverrides
    ): Promise<MarketTokenStructOutput[]>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getListingPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    makeMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "makeMarketItem(address,uint256,uint256)"(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MarketTokenMinted(uint256,address,uint256,address,address,uint256,bool)"(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: null,
      owner?: null,
      price?: null,
      sold?: null
    ): MarketTokenMintedEventFilter;
    MarketTokenMinted(
      itemId?: BigNumberish | null,
      nftContract?: string | null,
      tokenId?: BigNumberish | null,
      seller?: null,
      owner?: null,
      price?: null,
      sold?: null
    ): MarketTokenMintedEventFilter;
  };

  estimateGas: {
    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createMarketSale(address,uint256)"(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fetchItemsCreated(overrides?: CallOverrides): Promise<BigNumber>;

    "fetchItemsCreated()"(overrides?: CallOverrides): Promise<BigNumber>;

    fetchMarketTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "fetchMarketTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<BigNumber>;

    "fetchMyNFTs()"(overrides?: CallOverrides): Promise<BigNumber>;

    getListingPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getListingPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    makeMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "makeMarketItem(address,uint256,uint256)"(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createMarketSale(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createMarketSale(address,uint256)"(
      nftContract: string,
      itemId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fetchItemsCreated(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fetchItemsCreated()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fetchMarketTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fetchMarketTokens()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fetchMyNFTs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fetchMyNFTs()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getListingPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getListingPrice()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    makeMarketItem(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "makeMarketItem(address,uint256,uint256)"(
      nftContract: string,
      tokenId: BigNumberish,
      price: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
